# Site settings
title: Tanya Prasad
email: tanya.prasad@gmail.com
description: Final Year undergrad at BITS Pilani. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com/7anya
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/tanya-prasad
pinterest_url:
slack_url:
twitter_url: 
blog_url: https://one-to-tan.blogspot.com
youtube_url:

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "Microsoft"
    details:
      - date: "May 2022"
        position: "Software engineer"
        description: "Microsoft defender for Outlook"
  - company: "Red Hat inc"
    details:
      - date: "May 2021"
        position: "Intern"
        description: "Red Hat openshift Data Science"
   
  - company: "Google Summer of COde: AOSSIE"
    details:
      - date: "May 2022"
        position: "Mentor"
        description: "Peer to Peer messaging application"  
      - date: "May 2021"
        position: "Software developer"
        description: "Peer to Peer messaging application"
  - company: "National Informatics center"
    details:
      - date: "May 2020"
        position: "Intern"
        description: "Blockchain"

# Projects
# Note: The <style> in Work is somehow also applied to Projects! So no need to apply again in the file
projects:
  - title: "Project 1"
    date: "Some date"
    description: "Some description"
    link: "https://github.com/rutvora/rutvora.github.io"
  - title: "Project 2"
    date: "Some other date"
    description: "Some other description"
