# Site settings
title: Dimension
email: youremailaddress@gmail.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich
blog_url: https://rutvora.blogspot.com
youtube_url: https://www.youtube.com/channel/UCLaHH4xiZZADIYZ-SwTtY2w

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "Some company"
    details:
      - date: "October 2022"
        position: "Your position"
        description: "Some description"
      - date: "June 2022"
        position: "Different Position"
        description: "Different Description"
  - company: "Some other company"
    details:
      - date: "October 2020"
        position: "Your position"
        description: "Some description"
      - date: "June 2020"
        position: "Different Position"
        description: "Different Description"
