# Site settings
title: Rut Vora
email: contactme@rutvora.com
description: Incoming MS Computer Science Student at the University of British Columbia, Vancouver.  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Rut Vora
street_address: 
city: 
state: 
zip_code: 
country: 
phone:

icon: fa-r # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Social settings
facebook_url: https://www.facebook.com/rutvora
github_url: https://www.github.com/rutvora
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/rutvora
linkedin_url: https://www.linkedin.com/in/rutvora
pinterest_url:
slack_url:
twitter_url: 
blog_url: https://rutvora.blogspot.com
youtube_url: https://www.youtube.com/channel/UCLaHH4xiZZADIYZ-SwTtY2w

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "F5, Inc."
    details:
      - date: "Apr 2022 - "
        position: "Software Engineer II"
        description: "1. Working with eBPF for System Call Tracing <br/>2. Working with P4lang for customising network packet headers on the fly!"
      - date: "Sep '20 - Apr '20"
        position: "Software Engineer I"
        description: "1. Worked with WebAssembly and WebAssembly System Interface to create language-independent modules <br/>2. Created PoC to enable normal apps to use DPDK and F-Stack (deployed on SmartNICs)"
  - company: "Ericsson"
    details:
      - date: "Jul '19 - Dec '19"
        position: "Research Intern"
        description: "1. Published a <a href=\"https://doi.org/10.1201/9781003052098-34\">research Paper</a> on 5G connectivity solution in Hyperloop <br>2. Proposed architectures for implementing 5G in AR/VR, Home Automation etc."

# Projects
# Note: The <style> in Work is somehow also applied to Projects! So no need to apply again in the file
projects:
  - title: "Adaptive Video Streaming on UDP"
    date: "Apr '19 - Jun '19"
    description: "Dynamically determine video compression factors like spatial and temporal compression, rate factors and codecs"
    link: "https://github.com/rutvora/Intranet-Video-Caller/tree/master/GoLang/Video%20Caller"
  - title: "Firmware Verification/Update in IoT devices using Ethereum Blockchain"
    date: "Mar '19 - Apr '19"
    description: "Proposed architecture to verify firmware integrity in IoT devices (similar to \"Secure Boot\") using Smart Contracts on Ethereum"
    link: "https://github.com/RUTVORA/FIRMWARE_VERIFICATION-UPDATE_WITH_SMART_CONTRACTS"
  - title: "Communication without the Internet"
    date: "Oct '18"
    description: "Enabled communicating safety status of user during a natural disaster using Bluetooth/Wifi-Direct"
  - title: "Natural Disaster NavIC"
    date: "Feb '19"
    description: "Utilised 200-bit space in NavIC (Indian GPS counterpart) transmissions to send 10 safe locations and their status with 100m accuracy during a natural disaster (as a part of an ISRO hackathon)"
