name: Jekyll site CI

on:
  push:
    branches: [ "rutvora.com" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Jekyll
        # You may pin to the exact commit or the version.
        # uses: jerryjvl/jekyll-build-action@0bab4194a14ea47ae5ca609fc5b95aaadab40060
        uses: jerryjvl/jekyll-build-action@v1
        
      - name: Jekyll Action
        # You may pin to the exact commit or the version.
        # uses: lemonarc/jekyll-action@2d5e5a2316cd9d4b74ad33da527d6d9be5bff8d1
        uses: lemonarc/jekyll-action@1.0.0
        
      - name: Jekyll Build
        # You may pin to the exact commit or the version.
        # uses: kshehadeh/jekyll-s3-action@220371747871b9aa1b635fb30a57693891e37982
        uses: kshehadeh/jekyll-s3-action@0.1
        
        
